<a href="https://colab.research.google.com/github/carbotton/taller-deep-learning/blob/main/01/Clase01_Intro_PyTorch_letra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Introducción a PyTorch


[PyTorch](https://pytorch.org/) es una biblioteca de aprendizaje profundo de código abierto basada en el lenguaje de programación Python. Desarrollada por Facebook's AI Research lab, PyTorch se ha convertido en una de las herramientas más populares en el campo de la inteligencia artificial y el aprendizaje automático. En esta notebook, vamos a explorar los conceptos básicos de PyTorch con su unidad de cálculo básica, el [tensor](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html).

Esta notebook esta basada en:

- Joe Papa. (2021). _PyTorch Pocket Reference: Building and Deploying Deep Learning Models_. O'Reilly Media, Inc.
- [Learning PyTorch with Examples](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html)
- [d2l - Data Manipulation](https://d2l.ai/chapter_preliminaries/ndarray.html)
- [d2l - Linear Algebra](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

## ¿Qué es un tensor?

Un [tensor](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) es una matriz multidimensional que puede contener datos de diferentes tipos (por ejemplo, números enteros, flotantes, etc.). Los tensores son similares a los arreglos de NumPy, pero con la diferencia de que los tensores pueden ser utilizados en una GPU para acelerar los cálculos. En PyTorch, los tensores son la unidad básica de cálculo y se pueden crear de varias maneras.


<div style="text-align: center;">
    <img src="https://miro.medium.com/v2/resize:fit:720/format:webp/1*8jdzMrA33Leu3j3F6A8a3w.png" width="500" alt="PyTorch logo">
</div>

## Creación de tensores

Se pueden crear tensores de varias maneras en PyTorch. A continuación, se van a mostrar algunos ejemplos comunes de cómo crear tensores en PyTorch.

### Desde estructuras de datos

Podemos crear un tensor a partir de una lista de Python, una tupla, una matriz de NumPy, etc. Para ello, podemos utilizar la función [torch.tensor()](https://pytorch.org/docs/stable/generated/torch.tensor.html).

In [2]:
x = torch.tensor([1, 2, 3])  # creamos a partir de una lista
y = torch.tensor((1, 2, 3))  # creamos a partir de una tupla
z = torch.tensor(np.array([1, 2, 3]))  # creamos a partir de un array de numpy  (si se crea con as_tensor(np) comparte memoria)

print(f"{ x = }")
print(f"{ y = }")
print(f"{ z = }")

 x = tensor([1, 2, 3])
 y = tensor([1, 2, 3])
 z = tensor([1, 2, 3])


Probemos con diferentes dimensiones.

In [3]:
w = torch.tensor(5)  # 0 dimensiones - escalar
x = torch.tensor([5, 4, 3])  # 1 dimension - vector
y = torch.tensor([[5, 4, 3], [2, 1, 0]])  # 2 dimensiones - matriz
z = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # N dimensiones - tensor de orden N

print(f"{ w = }\n")
print(f"{ x = }\n")
print(f"{ y = }\n")
print(f"{ z = }")

 w = tensor(5)

 x = tensor([5, 4, 3])

 y = tensor([[5, 4, 3],
        [2, 1, 0]])

 z = tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Los tensores pueden contener datos de diferentes tipos, como enteros, flotantes, etc. Lo importante es que todos los elementos de un tensor deben ser del mismo tipo. Si no se especifica el tipo de datos, PyTorch inferirá el tipo de datos del tensor.
Para saber todos los tipos de datos que se pueden utilizar en PyTorch, puedes consultar la [documentación oficial](https://pytorch.org/docs/stable/tensors.html#data-types).

In [4]:
v = torch.tensor([1, 2, 3], dtype=torch.uint8)  # tipo de dato uint8 (0-255)
w = torch.tensor([1, 2, 3], dtype=torch.int32)  # tipo de dato int32
x = torch.tensor([1, 2, 3], dtype=torch.long)  # tipo de dato int64 o long
y = torch.tensor([1, 2, 3], dtype=torch.float32)  # tipo de dato float32
z = torch.tensor([False, True, False], dtype=torch.bool)  # tipo de dato booleano

print(f"{ v = }")
print(f"{ w = }")
print(f"{ x = }")
print(f"{ y = }")
print(f"{ z = }")

 v = tensor([1, 2, 3], dtype=torch.uint8)
 w = tensor([1, 2, 3], dtype=torch.int32)
 x = tensor([1, 2, 3])
 y = tensor([1., 2., 3.])
 z = tensor([False,  True, False])


Ejercicios:

- ¿Qué dato utilizarías para una imagen RGB?
  uint8
- ¿Qué dato utilizarías para el etiquetado de una imagen (clases 0-9)?
  
- ¿Qué dato utilizarías para los pesos de una red neuronal?
- ¿Qué dato utilizarías para las probabilidades de salida de un clasificador?
- ¿Qué dato utilizarías para una máscara binaria que indica píxeles válidos?

Podemos ver el tipo de datos de un tensor utilizando el atributo `dtype`.

In [5]:
print(f"{ v.dtype = }")
print(f"{ w.dtype = }")
print(f"{ x.dtype = }")
print(f"{ y.dtype = }")
print(f"{ z.dtype = }")

 v.dtype = torch.uint8
 w.dtype = torch.int32
 x.dtype = torch.int64
 y.dtype = torch.float32
 z.dtype = torch.bool


### Desde tensores existentes

Podemos crear un tensor a partir de un tensor existente utilizando el método [torch.clone()](https://pytorch.org/docs/stable/generated/torch.clone.html).



In [6]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = x  # y apunta a la misma dirección de memoria que x
z = x.clone()  # z apunta a una nueva dirección de memoria

y[0] = 100  # cambia el valor de x

print(f"{ x = }")
print(f"{ y = }")
print(f"{ z = }")

 x = tensor([100.,   2.,   3.])
 y = tensor([100.,   2.,   3.])
 z = tensor([1., 2., 3.])


> Tip: el método `clone()` es diferenciable, lo que significa que los gradientes se pueden propagar a través de él. Utiliza el método `detach()` si no quieres que los gradientes se propaguen.

Ejercicio: ¿Qué imprime el siguiente código?

```python
original = torch.tensor([10, 20, 30])
reference = original
copy = original.clone()
copy_reference = copy

original += 5
copy_reference -= 5

print(f"original = {original}")
print(f"reference = {reference}")
print(f"copy = {copy}")
print(f"copy_reference = {copy_reference}")
```

### Desde funciones

Existen varias funciones en PyTorch que nos permiten crear tensores con valores específicos. Algunas de estas funciones son:

- [torch.zeros()](https://pytorch.org/docs/stable/generated/torch.zeros.html): crea un tensor con todos los elementos establecidos en cero.
- [torch.ones()](https://pytorch.org/docs/stable/generated/torch.ones.html): crea un tensor con todos los elementos establecidos en uno.
- [torch.rand()](https://pytorch.org/docs/stable/generated/torch.rand.html): crea un tensor con valores aleatorios entre 0 y 1.
- [torch.randn()](https://pytorch.org/docs/stable/generated/torch.randn.html): crea un tensor con valores aleatorios de una distribución normal.
- [torch.arange()](https://pytorch.org/docs/stable/generated/torch.arange.html): crea un tensor con valores espaciados uniformemente dentro de un rango.
- [torch.full()](https://pytorch.org/docs/stable/generated/torch.full.html): crea un tensor con todos los elementos establecidos en un valor específico.


Muchos de estos métodos reciben como argumento la forma del tensor que queremos crear. Por ejemplo, si queremos crear un tensor de 2x3 con todos los elementos establecidos en cero, podemos hacerlo de la siguiente manera:

```python
torch.zeros(2, 3)
```

In [7]:
zeros = torch.zeros((2, 3))  # tensor de 2x3 con ceros (float32)
print(f"{ zeros = }\n")

zeros = torch.zeros((2, 3), dtype=torch.uint8)  # tensor de 2x3 con ceros (uint8)
print(f"{ zeros = }")

 zeros = tensor([[0., 0., 0.],
        [0., 0., 0.]])

 zeros = tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)


In [8]:
ones = torch.ones((5,))  # tensor de 5 elementos con unos
print(f"{ ones = }\n")

 ones = tensor([1., 1., 1., 1., 1.])



In [9]:
rand = torch.rand(3, 4)  # tensor de 3x4 con valores aleatorios entre 0 y 1
print(f"{ rand = }\n")

randn = torch.randn(
    3, 4
)  # tensor de 3x4 con valores aleatorios de una distribución normal
print(f"{ randn = }\n")

 rand = tensor([[0.8570, 0.1923, 0.1336, 0.5876],
        [0.3674, 0.9699, 0.0257, 0.1681],
        [0.6807, 0.8094, 0.6808, 0.0420]])

 randn = tensor([[-0.3020,  0.3789,  1.0182,  0.3817],
        [ 1.3319,  0.9042,  1.0334, -0.7012],
        [-0.9756,  0.7985, -0.6080,  0.3230]])



In [10]:
arrange = torch.arange(0, 100, 5)  # tensor con valores de 0 a 100 con paso de 5
print(f"{ arrange = }\n")

 arrange = tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])



In [11]:
full_of_5 = torch.full((3, 3), 5)  # tensor de 3x3 con todos los elementos en 5
print(f"{ full_of_5 = }\n")

 full_of_5 = tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])



#### Funciones `_like`

A veces, necesitamos crear un tensor con la misma forma que otro tensor. Para ello, PyTorch proporciona funciones que nos permiten crear tensores con la misma forma que otro tensor. Algunos ejemplos de estas funciones son:

- [torch.zeros_like()](https://pytorch.org/docs/stable/generated/torch.zeros_like.html): crea un tensor con la misma forma que otro tensor con todos los elementos establecidos en cero.
- [torch.ones_like()](https://pytorch.org/docs/stable/generated/torch.ones_like.html): crea un tensor con la misma forma que otro tensor con todos los elementos establecidos en uno.
- [torch.rand_like()](https://pytorch.org/docs/stable/generated/torch.rand_like.html): crea un tensor con la misma forma que otro tensor con valores aleatorios entre 0 y 1.
- ...

In [12]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(f"{ torch.zeros_like(x) = }\n")
print(f"{ torch.zeros_like(y) = }\n")

print(f"{ torch.ones_like(x) = }\n")
print(f"{ torch.ones_like(y) = }\n")

print(f"{ torch.rand_like(x) = }\n")
print(f"{ torch.rand_like(y) = }\n")

 torch.zeros_like(x) = tensor([0., 0., 0.])

 torch.zeros_like(y) = tensor([[0., 0., 0.],
        [0., 0., 0.]])

 torch.ones_like(x) = tensor([1., 1., 1.])

 torch.ones_like(y) = tensor([[1., 1., 1.],
        [1., 1., 1.]])

 torch.rand_like(x) = tensor([0.4677, 0.8519, 0.2361])

 torch.rand_like(y) = tensor([[0.3329, 0.9146, 0.9359],
        [0.4330, 0.5204, 0.0289]])



## Atributos de un tensor

Los tensores en PyTorch tienen varios atributos que nos permiten acceder a información sobre el tensor. Algunos de los atributos más comunes son:

- [dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch-dtype): devuelve el tipo de datos del tensor.
- [shape](https://pytorch.org/docs/stable/generated/torch.Tensor.shape.html): devuelve la forma/dimensiones del tensor. También podemos utilizar el método [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) para obtener la forma del tensor.
- [ndim](https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html): devuelve el número de dimensiones del tensor. También podemos utilizar el método [dim()](https://pytorch.org/docs/stable/generated/torch.Tensor.dim.html) para obtener el número de dimensiones del tensor.
- [device](https://pytorch.org/docs/stable/generated/torch.Tensor.device.html): devuelve el dispositivo en el que se encuentra el tensor (CPU MPS o GPU). MPS es de MAC.
- [requires_grad](https://pytorch.org/docs/stable/generated/torch.Tensor.requires_grad.html): indica si el tensor requiere cálculo de gradientes.


In [13]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(f"{ x.shape = }")
print(f"{ x.size() = }\n")

print(
    f"{ y.size() = }"
)  # si no se pone argumento, devuelve una tupla con las dimensiones
print(f"{ y.size(0) = }")  # devuelve el tamaño de la primera dimensión
print(f"{ y.size(1) = }")  # devuelve el tamaño de la segunda dimensión

 x.shape = torch.Size([3])
 x.size() = torch.Size([3])

 y.size() = torch.Size([2, 3])
 y.size(0) = 2
 y.size(1) = 3


In [14]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(f"{ x.ndim = }")
print(f"{ x.dim() = }\n")

print(f"{ y.ndim = }")
print(f"{ y.dim() = }")

 x.ndim = 1
 x.dim() = 1

 y.ndim = 2
 y.dim() = 2


In [15]:
x = torch.tensor([1, 2, 3])

print(f"{x.device = }")  # cpu es el dispositivo por defecto

if torch.cuda.is_available():  # si hay una GPU disponible (y cuda está instalado)
    x = x.to("cuda")  # movemos el tensor a la GPU
    print("x movido a la GPU")
    print(f"{x.device = }")

if (
    torch.backends.mps.is_available()
):  # si hay un MPS disponible (https://pytorch.org/docs/stable/mps.html)
    x = x.to("mps")
    print("x movido a MPS")
    print(f"{x.device = }")

x.device = device(type='cpu')


Otra forma es crear el tensor directamente en el dispositivo que queremos utilizando el argumento `device`. Por ejemplo, si queremos crear un tensor en la GPU, podemos hacerlo de la siguiente manera:

```python
torch.zeros(2, 3, device='cuda')
```

Es importante verificar que el dispositivo esté disponible antes de crear un tensor en él.

## Operadores aritméticos

Existen varias operaciones que podemos realizar con tensores en PyTorch. Algunas de las operaciones más comunes son:

- [Suma](https://pytorch.org/docs/stable/generated/torch.add.html): podemos sumar dos tensores utilizando el operador `+` o la función `torch.add()`.
- [Resta](https://pytorch.org/docs/stable/generated/torch.sub.html): podemos restar dos tensores utilizando el operador `-` o la función `torch.sub()`.
- [Multiplicación](https://pytorch.org/docs/stable/generated/torch.mul.html): podemos multiplicar dos tensores utilizando el operador `*` o la función `torch.mul()`.
- [División](https://pytorch.org/docs/stable/generated/torch.div.html): podemos dividir dos tensores utilizando el operador `/` o la función `torch.div()`.

In [16]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([1, 5, 10])

print(f"{x + y = }")
print(f"{x - y = }")
print(f"{x * y = }")
print(f"{x / y = }")

x + y = tensor([ 2,  7, 13])
x - y = tensor([ 0, -3, -7])
x * y = tensor([ 1, 10, 30])
x / y = tensor([1.0000, 0.4000, 0.3000])


### Operaciones in-place

PyTorch también proporciona operaciones in-place que modifican el tensor original. Estas operaciones tienen un guion bajo al final del nombre de la función. Estas operaciones son más eficientes en términos de memoria y tiempo de ejecución, ya que no crean un nuevo tensor.

In [17]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([1, 5, 10])

x.add(y)  # suma x e y y guarda el resultado en una nueva variable
print(f"{ x = }")

x.add_(y)  # suma y guarda el resultado en x
print(f"{ x = }")

 x = tensor([1, 2, 3])
 x = tensor([ 2,  7, 13])


## Broadcasting

PyTorch también admite [broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html), que es una técnica que permite a PyTorch realizar operaciones entre tensores de diferentes formas. PyTorch realiza broadcasting automáticamente cuando es posible. Por ejemplo, si tenemos un tensor de forma (2, 3) y queremos sumar un escalar a él, PyTorch realizará broadcasting automáticamente para que la operación sea válida. Toma la [idea de NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html) y la implementa de manera eficiente en PyTorch.

Reglas de broadcasting:

- Cada tensor tiene al menos una dimensión.
- Al iterar sobre los tamaños de dimensión, empezando por la dimensión final (der a izq), los tamaños de dimensión deben cumplir con alguna de estas condiciones:
    - ser iguales
    - uno de ellos es 1
    - uno de ellos no existe.

In [18]:
x = torch.empty(5, 7, 3)
y = torch.empty(5, 7, 3)
# son broadcasteables porque sus dimensiones son iguales

x = torch.empty((0,))
y = torch.empty(2, 2)
# no son broadcasteables porque x no tiene dimensiones (rompe la regla 1)

x = torch.empty(5, 3, 4, 1)
y = torch.empty(3, 1, 1)
# x e y son broadcastables.
# 1st dimension: son iguales (el 1 con  el 1)
# 2nd dimension: y tiene un tamaño de 1 (el 4 con el 1)
# 3rd dimension: son iguales (el 3 con el 3)
# 4th dimension: y falta (el 5 con nada)

x = torch.empty(5, 2, 4, 1)
y = torch.empty(3, 1, 1)
# no son broadcasteables porque la 3nd dimension x es diferente de la 3rd dimension de y (2 != 3)

In [19]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([3])
z = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(f"{x.size() = }")
print(f"{y.size() = }")
print(f"{z.size() = }\n")

print(f"{x + y = }")
print(f"{x + z = }")

x.size() = torch.Size([3])
y.size() = torch.Size([1])
z.size() = torch.Size([2, 3])

x + y = tensor([4, 5, 6])
x + z = tensor([[2, 4, 6],
        [5, 7, 9]])


Ejercicios:
```python
a = torch.randn(3, 1, 5)    # shape: [3, 1, 5]
b = torch.randn(2, 4, 1)    # shape: [2, 4, 1]
# ¿Se puede hacer: result = a + b?


x = torch.randn(128, 1, 1)     # shape: [128, 1, 1]
y = torch.randn(1, 64, 32)     # shape: [1, 64, 32]
# ¿Se puede hacer: result = x * y?

tensor_a = torch.randn(5, 3, 2)    # shape: [5, 3, 2]
tensor_b = torch.randn(3, 4)       # shape: [3, 4]
# ¿Se puede hacer: result = tensor_a - tensor_b?
```

## Indexación y slicing

Podemos acceder a los elementos de un tensor utilizando la indexación y el slicing. La indexación en PyTorch es similar a la indexación en NumPy. Podemos acceder a los elementos de un tensor utilizando corchetes `[]`. También podemos utilizar el slicing para acceder a subtensores de un tensor. La indexación y el slicing en PyTorch son de estilo Python, lo que significa que el índice de inicio es inclusivo y el índice de parada es exclusivo.

In [20]:
x = torch.tensor([1, 2, 3, 4, 5])

print(f"{x[0] = }")  # primer elemento
print(f"{x[2] = }")  # tercer elemento
print(f"{x[-1] = }\n")  # último elemento

print(f"{x[1:3] = }")  # elementos 1 y 2
print(f"{x[2:] = }")  # elementos desde el 2 en adelante
print(f"{x[:4] = }\n")  # elementos hasta el 4

print(f"{x[::2] = }")  # elementos de 2 en 2

x[0] = tensor(1)
x[2] = tensor(3)
x[-1] = tensor(5)

x[1:3] = tensor([2, 3])
x[2:] = tensor([3, 4, 5])
x[:4] = tensor([1, 2, 3, 4])

x[::2] = tensor([1, 3, 5])


Quizás nos interesaría tomar un valor específico de un tensor. Para ello, podemos utilizar el método [item()](https://pytorch.org/docs/stable/generated/torch.Tensor.item.html). <- Muy útil para obtener un valor escalar de un tensor, por ejemplo la loss.

In [21]:
x = torch.tensor([1, 2, 3, 4, 5])

print(f"{x[0] = }")
print(f"{x[0].item() = }")  # solo funciona con tensores de un solo elemento

x[0] = tensor(1)
x[0].item() = 1


In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # matriz 3x3

print(f"{x[0, 0] = }")  # primer elemento
print(f"{x[1, 2] = }")  # elemento de la segunda fila y tercera columna
print(f"{x[-1, -1] = }\n")  # último elemento de la última fila

print(f"{x[1, :] = }")  # segunda fila
print(f"{x[:, 2] = }")  # tercera columna
print(
    f"{x[1:, :2] = }"
)  # desde la segunda fila hasta el final y desde la primera columna hasta la segunda

x[0, 0] = tensor(1)
x[1, 2] = tensor(6)
x[-1, -1] = tensor(9)

x[1, :] = tensor([4, 5, 6])
x[:, 2] = tensor([3, 6, 9])
x[1:, :2] = tensor([[4, 5],
        [7, 8]])


Ten en cuenta que la indexación y el slicing en PyTorch devuelven [vistas](https://pytorch.org/docs/stable/tensor_view.html) del tensor original, no copias. Esto significa que si modificamos el tensor resultante, también se modificará el tensor original.

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # matriz 3x3
y = x[:, 1] # segunda columna

y[0] = 100  # cambia el valor de x

print(f"{x = }\n")

# podemos chequear si dos tensores comparten memoria
if x.untyped_storage().data_ptr() == y.untyped_storage().data_ptr():
    print("x e y comparten memoria")

x = tensor([[  1, 100,   3],
        [  4,   5,   6],
        [  7,   8,   9]])

x e y comparten memoria


### Mascaras booleanas

Podemos utilizar máscaras booleanas para indexar tensores en PyTorch. Una máscara booleana es un tensor que contiene valores booleanos (True o False) y se utiliza para seleccionar elementos de un tensor. Veamos algunos ejemplos de cómo utilizar máscaras booleanas en PyTorch.

In [24]:
mask = torch.tensor([True, False, True, True])
x = torch.tensor([1, 2, 3, 4])

print(f"{x[mask] = }")
print(f"{x > 2 = }")
print(f"{x[x > 2] = }")
print(f"{(x * mask).sum() = }")

x[mask] = tensor([1, 3, 4])
x > 2 = tensor([False, False,  True,  True])
x[x > 2] = tensor([3, 4])
(x * mask).sum() = tensor(8)


In [25]:
mask = torch.tensor([True, False, True])
x = torch.tensor([1, 2, 3])

y = torch.zeros_like(x)
y[mask] = x[mask]

print(f"{y = }")

y = tensor([1, 0, 3])


Ejercicios: Qué imprime el siguiente código?

```python
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # matriz 3x3
mask = torch.tensor([True, False, True])  # máscara booleana
print(f"{x[mask] = }")
print(f"{x > 2 = }")
print(f"{x[x > 2] = }")
print(f"{(x * mask).sum() = }")
```

## Funciones de reducción y agregación

PyTorch proporciona varias funciones de reducción que nos permiten reducir un tensor a un solo valor. Algunas de las funciones de reducción más comunes son:

- [torch.sum()](https://pytorch.org/docs/stable/generated/torch.sum.html): calcula la suma de todos los elementos de un tensor.
- [torch.mean()](https://pytorch.org/docs/stable/generated/torch.mean.html): calcula la media de todos los elementos de un tensor.
- [torch.max()](https://pytorch.org/docs/stable/generated/torch.max.html): calcula el valor máximo de un tensor.
- [torch.min()](https://pytorch.org/docs/stable/generated/torch.min.html): calcula el valor mínimo de un tensor.
- [torch.argmax()](https://pytorch.org/docs/stable/generated/torch.argmax.html): devuelve el índice del valor máximo de un tensor.
- [torch.argmin()](https://pytorch.org/docs/stable/generated/torch.argmin.html): devuelve el índice del valor mínimo de un tensor.

Estas funciones también aceptan un argumento `dim` que nos permite especificar la dimensión a lo largo de la cual queremos realizar la reducción.

In [26]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)

print(f"{torch.sum(x) = }")  # suma de todos los elementos
print(f"{torch.sum(x, dim=0) = }")  # suma de cada columna
print(f"{torch.sum(x, dim=1) = }\n")  # suma de cada fila

print(f"{torch.mean(x) = }")  # media de todos los elementos
print(f"{torch.mean(x, dim=0) = }")  # media de cada columna
print(f"{torch.mean(x, dim=1) = }\n")  # media de cada fila

print(f"{torch.max(x) = }")  # máximo de todos los elementos
print(f"{torch.max(x, dim=0) = }")  # máximo de cada columna
print(f"{torch.max(x, dim=1) = }\n")  # máximo de cada fila

print(f"{torch.min(x) = }")  # mínimo de todos los elementos
print(f"{torch.min(x, dim=0) = }")  # mínimo de cada columna
print(f"{torch.min(x, dim=1) = }\n")  # mínimo de cada fila

print(
    f"{torch.argmax(x) = }"
)  # índice del máximo de todos los elementos, como es una matriz, devuelve el índice en el array plano
print(f"{torch.argmax(x, dim=0) = }")  # índice del máximo de cada columna
print(f"{torch.argmax(x, dim=1) = }\n")  # índice del máximo de cada fila

torch.sum(x) = tensor(45.)
torch.sum(x, dim=0) = tensor([12., 15., 18.])
torch.sum(x, dim=1) = tensor([ 6., 15., 24.])

torch.mean(x) = tensor(5.)
torch.mean(x, dim=0) = tensor([4., 5., 6.])
torch.mean(x, dim=1) = tensor([2., 5., 8.])

torch.max(x) = tensor(9.)
torch.max(x, dim=0) = torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
torch.max(x, dim=1) = torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))

torch.min(x) = tensor(1.)
torch.min(x, dim=0) = torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
torch.min(x, dim=1) = torch.return_types.min(
values=tensor([1., 4., 7.]),
indices=tensor([0, 0, 0]))

torch.argmax(x) = tensor(8)
torch.argmax(x, dim=0) = tensor([2, 2, 2])
torch.argmax(x, dim=1) = tensor([2, 2, 2])



## Combinación y división

PyTorch proporciona varias funciones que nos permiten combinar y dividir tensores. Algunas de las funciones más comunes son:

- [torch.cat()](https://pytorch.org/docs/stable/generated/torch.cat.html): combina varios tensores a lo largo de una dimensión específica.
- [torch.stack()](https://pytorch.org/docs/stable/generated/torch.stack.html): apila varios tensores a lo largo de una nueva dimensión.
- [torch.split()](https://pytorch.org/docs/stable/generated/torch.split.html): divide un tensor en varias partes a lo largo de una dimensión específica.
- [torch.chunk()](https://pytorch.org/docs/stable/generated/torch.chunk.html): divide un tensor en varias partes a lo largo de una dimensión específica.
- [torch.squeeze()](https://pytorch.org/docs/stable/generated/torch.squeeze.html): elimina dimensiones de tamaño 1 de un tensor.
- [torch.unsqueeze()](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html): agrega una dimensión de tamaño 1 a un tensor.
- [torch.reshape()](https://pytorch.org/docs/stable/generated/torch.reshape.html): cambia la forma de un tensor.

Existen muchas más funciones que nos permiten combinar y dividir tensores en PyTorch. Puedes consultar la [documentación oficial](https://pytorch.org/docs/stable/torch.html) para obtener más información sobre estas funciones.

In [27]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
y = torch.tensor([5, 4, 3, 2, 1, 0])

print(f"{torch.cat((x, y)) = }\n")  # concatenación de tensores
print(f"{torch.stack((x, y)) = }\n")  # apilamiento de tensores
print(f"{torch.split(x, 2) = }\n")  # división de un tensor en partes de tamaño 2
print(f"{torch.chunk(x, 2) = }\n")  # división de un tensor en 2 partes

print(
    f"{torch.squeeze(torch.zeros(1, 2, 1, 2)).size() = }\n"
)  # elimina las dimensiones de tamaño 1
print(f"{torch.unsqueeze(torch.zeros(2, 2), 0).size() = }")  # añade una dimensión al principio

torch.cat((x, y)) = tensor([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 0])

torch.stack((x, y)) = tensor([[1, 2, 3, 4, 5, 6],
        [5, 4, 3, 2, 1, 0]])

torch.split(x, 2) = (tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))

torch.chunk(x, 2) = (tensor([1, 2, 3]), tensor([4, 5, 6]))

torch.squeeze(torch.zeros(1, 2, 1, 2)).size() = torch.Size([2, 2])

torch.unsqueeze(torch.zeros(2, 2), 0).size() = torch.Size([1, 2, 2])


In [28]:
x = torch.arange(9)
print(f"{torch.reshape(x, (3, 3)).size() = }")  # reorganiza los elementos en una matriz 3x3
print(
    f"{torch.reshape(x, (3, -1)).size() = }"
)  # -1 significa que se infiere el tamaño de esa dimensión
print(f"{torch.reshape(x, (-1, 3)).size() = }\n")

x = torch.tensor([1, 2, 3, 4, 5, 6])
print(f"{torch.reshape(x, (2, 3)).size() = }")  # reorganiza los elementos en una matriz 2x3
print(f"{torch.reshape(x, (3, 2)).size() = }")  # reorganiza los elementos en una matriz 3x2
print(f"{torch.reshape(x, (6, -1)).size() = }")  # reorganiza los elementos en una matriz 6x1

torch.reshape(x, (3, 3)).size() = torch.Size([3, 3])
torch.reshape(x, (3, -1)).size() = torch.Size([3, 3])
torch.reshape(x, (-1, 3)).size() = torch.Size([3, 3])

torch.reshape(x, (2, 3)).size() = torch.Size([2, 3])
torch.reshape(x, (3, 2)).size() = torch.Size([3, 2])
torch.reshape(x, (6, -1)).size() = torch.Size([6, 1])


## Comparaciones

### Elemento a elemento

Podemos realizar comparaciones elemento a elemento entre dos tensores utilizando los operadores de comparación estándar (`==`, `!=`, `>`, `<`, `>=`, `<=`). Estos operadores devuelven un tensor de tipo `bool` con el mismo tamaño que los tensores de entrada.

In [29]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([3, 2, 1])

print(f"{ x == y = }")  # También se puede usar torch.eq(x, y)
print(f"{ x < y = }")  # También se puede usar torch.lt(x, y)
print(f"{ x > y = }")  # También se puede usar torch.gt(x, y)
print(f"{ x != y = }")  # También se puede usar torch.ne(x, y)
print(f"{ x <= y = }")  # También se puede usar torch.le(x, y)
print(f"{ x >= y = }")  # También se puede usar torch.ge(x, y)
print(f"{ x % 2 == 0 = }\n")  # También se puede usar torch.ge(x, y)

print(f"{ torch.where(x < y, x, y) = }")  # si x < y, devuelve x, sino y

 x == y = tensor([False,  True, False])
 x < y = tensor([ True, False, False])
 x > y = tensor([False, False,  True])
 x != y = tensor([ True, False,  True])
 x <= y = tensor([ True,  True, False])
 x >= y = tensor([False,  True,  True])
 x % 2 == 0 = tensor([False,  True, False])

 torch.where(x < y, x, y) = tensor([1, 2, 1])


### De reducción

PyTorch también proporciona funciones de comparación de reducción que nos permiten comparar un tensor con un valor específico. Algunas de las funciones de comparación de reducción más comunes son:

- [torch.all()](https://pytorch.org/docs/stable/generated/torch.all.html): devuelve `True` si todos los elementos de un tensor son verdaderos.
- [torch.any()](https://pytorch.org/docs/stable/generated/torch.any.html): devuelve `True` si algún elemento de un tensor es verdadero.

In [30]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([3, 2, 1])

print(f"{torch.all(x > 0) = }")  # si todos los elementos son mayores a 0
print(f"{torch.any(x < 0) = }")  # si algún elemento es menor a 0
print(f"{torch.all(x > y) = }")  # si todos los elementos de x son mayores a los de y

torch.all(x > 0) = tensor(True)
torch.any(x < 0) = tensor(False)
torch.all(x > y) = tensor(False)


## Uso de GPU

En PyTorch, podemos utilizar una GPU para acelerar los cálculos. En la siguiente celda contrastamos el tiempo que tarda en realizar una operación en una CPU y en una GPU.

In [31]:
x = torch.rand(2, 900000)
y = torch.randn(900000, 200)

print('CPU time:')
%timeit -n 5 -r 3 torch.mm(x, y) # https://docs.python.org/3/library/timeit.html

if torch.cuda.is_available():
    x = x.to('cuda')
    y = y.to('cuda')

    print('\nGPU time:')
    %timeit -n 5 -r 3 torch.mm(x, y)

if torch.backends.mps.is_available():
    x = x.to('mps')
    y = y.to('mps')

    print('\nMPS time:')
    %timeit -n 5 -r 3 torch.mm(x, y)  # MPS es para Mac con chip M1/M2

CPU time:
115 ms ± 3.11 ms per loop (mean ± std. dev. of 3 runs, 5 loops each)


# Ejercicios

1. Crear un tensor de 2x3 con valores aleatorios entre 0 y 1.
2. Crear un tensor de 3x3 con todos los elementos establecidos en cero.
3. Crear un tensor de dim 1 de 10 elementos con valores aleatorios con media 5 y varianza 1.
4. Crear una función que tome un tensor y devuelva el tensor elevado al cuadrado.
    ```python
    def square_tensor(tensor):
        pass
    ```
5. Crear una funcion que tome N y M (int) y retorne un tensor de NxM cuyos elementos sean los primeros números pares. Si N=2 y M=3 entonces [[0, 2, 4], [6, 8, 10]].
    ```python
    def even_tensor(n, m):
        pass
    ```
6. Crear una función que tome un tensor y devuelva el valor máximo y mínimo del tensor.
    ```python
    def min_max_tensor(tensor):
        pass
    ```
7. Crear una función que tome un tensor y devuelva la media y desviación estándar del tensor.
    ```python
    def mean_std_tensor(tensor):
        pass
    ```
8. Crear una función que tome un tensor de dimensión 1 y devuelva el tensor con los elementos en orden inverso. Ver: [torch.flip()](https://pytorch.org/docs/stable/generated/torch.flip.html).
    ```python
    def reverse_tensor(tensor):
        pass
    ```
9. Crear un tensor de NxM con valores aleatorios, obtener la suma de las fila y multiplicar por un valor constante.
    ```python
    def row_sum_prod(n, m, constant):
        pass
    ```
10. Crear una función que tome dos tensores y determine si existe algún elemento común entre ellos (en la misma posición).
    ```python
    def has_common_elements(tensor1, tensor2):
        pass
    ```
11. Crear una función que tome un tensor y devuelva el tensor con los elementos únicos.
    ```python
    def unique_elements(tensor):
        pass
    ```
12. Crear una función que tome dos tensores y retorna un tensor con los elementos comunes (en la misma posición).
    ```python
    def common_elements(tensor1, tensor2):
        pass
    ```

In [32]:
# 1. Crear un tensor de 2x3 con valores aleatorios entre 0 y 1.

tensor = torch.rand(2, 3)
print(tensor)


tensor([[0.6153, 0.2003, 0.0359],
        [0.5832, 0.0885, 0.8376]])


In [33]:
# 2. Crear un tensor de 3x3 con todos los elementos establecidos en cero.

tensor = torch.zeros(3,3)
print(tensor)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [34]:
# 3. Crear un vector de 10 elementos con valores aleatorios con media 5 y varianza 1.
# Crear un tensor de dim 1 de 10 elementos con valores aleatorios con media 5 y varianza 1.


#The torch.randn() function in PyTorch generates a tensor filled with random numbers drawn from a standard normal distribution.
#This means the generated numbers have:
#Mean: 0
#Variance: 1
# => mean + 5

tensor = torch.randn(10)
tensor = tensor - tensor.mean() + 5 # si hacia solamente torch.randn(10) + 5, no me daba exacto...

print(tensor.mean())




tensor(5.)


In [35]:
# 4. Crear una función que tome un tensor y devuelva el tensor elevado al cuadrado.


def square_tensor(tensor):
    tensor = tensor * tensor
    return tensor


print(square_tensor(torch.tensor([1, 2, 3])))  # tensor([1, 4, 9])


tensor([1, 4, 9])


In [36]:
# 5. Crear una funcion que tome N y M (int) y retorne un tensor de NxM cuyos elementos sean los primeros números pares. Si N=2 y M=3 entonces [[0, 2, 4], [6, 8, 10]].


def even_tensor(n, m):
    tensor = torch.arange(0, n*m*2, 2).reshape(n, m)  # start, end, step ; multiplico n*m*2 porque como en cada paso salteo uno no me da para llegar al shape de NxM
    print(tensor)
    return tensor

even_tensor(2, 3)  # tensor([[0, 2, 4], [6, 8, 10]])

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])


tensor([[ 0,  2,  4],
        [ 6,  8, 10]])

In [37]:
# 6. Crear una función que tome un tensor y devuelva el valor máximo y mínimo del tensor.


def min_max_tensor(tensor):
    return tensor.max(), tensor.min()

print(min_max_tensor(torch.tensor([1, 2, 3, 4, 5])))  # (5, 1)

(tensor(5), tensor(1))


In [38]:
# 7. Crear una funcion que tome tensor y devuelva la media y desviación estándar del tensor.

def mean_std_tensor(tensor):
  return tensor.mean(), tensor.std()


print(mean_std_tensor(torch.arange(10, dtype=torch.float32)))  # (4.5, 3.027..)

(tensor(4.5000), tensor(3.0277))


In [39]:
# 8. Crear una función que tome un tensor de dimensión 1 y devuelva el tensor con los elementos en orden inverso.


def reverse_tensor(tensor):
     return tensor.flip(0)  # dar vuelta elementos del eje 0



print(reverse_tensor(torch.tensor([1, 2, 3, 4, 5])))  # tensor([5, 4, 3, 2, 1])

tensor([5, 4, 3, 2, 1])


In [40]:
# 9. Crear un tensor de NxM con valores aleatorios, obtener la suma de las fila y multiplicar por un valor constante.


def row_sum_prod(n, m, constant):
    tensor = torch.rand(n, m)
    #print("tensor ", tensor)
    row_sum = tensor.sum(dim=1)
    #print("row_sum ", row_sum)
    tensor = tensor * constant
    #print("tensor x const ", tensor)
    return tensor, row_sum


print(row_sum_prod(2, 3, 2))  # tensor([_, _])

(tensor([[0.5595, 0.5635, 1.7708],
        [1.6698, 1.3742, 0.5199]]), tensor([1.4469, 1.7820]))


In [41]:
# 10. Crear una función que tome dos tensores y determine si existe algún elemento común entre ellos (en la misma posición).


def has_common_elements(tensor1, tensor2):
    for i in range(len(tensor1)):
        if tensor1[i] == tensor2[i]:
            return True
    return False


print(
    has_common_elements(torch.tensor([1, 2, 3, 4, 5]), torch.tensor([1, 5, 3, 4, 2]))
)  # True
print(
    has_common_elements(torch.tensor([1, 2, 3, 4, 5]), torch.tensor([5, 4, 1, 2, 3]))
)  # False

True
False


In [42]:
# 11. Crear una función que tome un tensor y devuelva el tensor (dim=1) con los elementos únicos.


def unique_elements(tensor):
    return tensor.unique()

print(unique_elements(torch.tensor([1, 2, 2, 1, 1, 3, 2, 2])))  # tensor([1, 2, 3])
print(
    unique_elements(torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 4]]))
)  # tensor([1, 2, 3, 4])

tensor([1, 2, 3])
tensor([1, 2, 3, 4])


In [43]:
# 12. Crear una función que tome dos tensores y retorna un tensor con los elementos comunes (en la misma posición).

def common_elements(tensor1, tensor2):
    elems = []
    for i in range(len(tensor1)):
        if tensor1[i] == tensor2[i]:
            elems.append(tensor1[i])
    return torch.tensor(elems)

print(common_elements(torch.tensor([1, 2, 3, 4, 5]), torch.tensor([1, 5, 3, 4, 2]))) # tensor([1, 3, 4])

tensor([1, 3, 4])
